name: nest

services:
  database:
    env_file: .env
    image: bitnami/postgresql
    ports:
      - ${DB_PORT}:5432
    expose:
      - 5432
    volumes:
      - storage_db:/var/lib/postgres/data
      # - ./data/pg:/data/postgres
    environment:
      POSTGRESQL_USERNAME: ${DB_USERNAME}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRESQL_DATABASE: ${DB_DATABASE}

  cache:
    container_name: nest-clean-cache
    image: bitnami/redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

volumes:
  storage_db: